article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard,name = "dashboard"),
    path('addarticle/', views.addArticle,name = "addarticle"),
    path('article/<int:id>', views.detail,name = "detail"),
    path('update/<int:id>', views.updateArticle,name = "update"),
    path('delete/<int:id>', views.deleteArticle,name = "delete"),
    path('', views.articles,name = "articles"),
    path('comment/<int:id>', views.addComment,name = "comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "user"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),
]

article/models.py
from django.db import models

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length = 50,verbose_name="Başlık")
    content = models.TextField(verbose_name="İçerik")
    created_date = models.DateTimeField(auto_now = True,verbose_name="Tarih")
    article_image = models.FileField(blank=True,null=True,verbose_name="Fotoğraf")
    def __str__ (self):
        return self.title
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name="isim")
    comment_content = models.CharField(max_length = 500,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now = True,verbose_name="Tarih")
    def __str__ (self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','content','article_image']

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı:")
    password = forms.CharField(label = "Şifre:", widget = forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50, label = "Kullanıcı Adı:")
    password = forms.CharField(max_length = 50, label = "Şifre:", widget = forms.PasswordInput)
    confirm = forms.CharField(max_length = 50, label = "Doğrula:", widget = forms.PasswordInput)

    def clean(self):
       username = self.cleaned_data.get("username")
       password = self.cleaned_data.get("password")
       confirm = self.cleaned_data.get("confirm")

       if password and confirm and password != confirm:
           raise forms.ValidationError("Parola Hatalı!")
       values = {
                "username" : username,
                "password" : password,
                "confirm" : confirm,
                }
       return values  

article/views.py
from django.shortcuts import render,HttpResponse,redirect,reverse,get_object_or_404
from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Article,Comment
# Create your views here.
def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
   
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")
@login_required(login_url ="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {"articles":articles}
    return render(request,"dashboard.html",context)
@login_required(login_url ="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Eklendi")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{'form':form})

def detail(request,id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id=id)
    comments = article.comments.all()
    return render(request,"detail.html",{'article':article,'comments':comments})

@login_required(login_url ="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Güncellendi")
        return redirect("article:dashboard")
    else:
        return render(request,"update.html",{'form':form})
@login_required(login_url ="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi")
    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author,comment_content = comment_content)
        newComment.article = article
        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render,redirect
from . forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages

def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username = username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.success(request,"Başarıyla Kayıt Oldunuz")
        return redirect("index")
    context = { "form" : form}
    return render(request,"register.html",context)

def loginUser(request):
    form = LoginForm(request.POST or None)
    context = { "form" : form}
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)
        if user is None:
            messages.warning(request,"Kullanıcı adı veya şifre hatalı")
            return render(request,"login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)

def logoutUser(request):
    logout(request)
    messages.success(request,"Bir daha da gelme buraya. Pezevenk!")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}

{% block body %}
 <h2>Hakkımızda</h2>
 <hr>
 Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.
 <hr>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="form-group">
    <div class="form-group">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data"> 
         {% csrf_token %}
         {{form|crispy}}
         <br>
        <button type="submit" class ="btn btn-warning">Gönder</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

        <h3>Makaleler</h3>
        <hr>
        {% if articles %}
          <form>
          {% csrf_token %}
         <input type ="text" name = "keyword" class = "input-sm" maxlenght = "64" placeholder = "Ara...">
         <button type ="submit" class = "btn btn-primary">Ara</button>
         </form>
         <hr>
          {% endif %}
        {% if articles %}
        {% for article in articles %}
        <div class="row">

       <!-- Post Content Column -->
       <div class="col-lg-8">

        <!-- Title -->
        <a href="{% url 'article:detail' article.id %}"><h5 class="mt-2">{{article.title}}</h5></a>

        <!-- Author -->
        <h4  class="mt-2"><p class="lead" >

          <a>{{article.author.username}} tarafından yayınlandı.</a>
        </p>
        </h4>
        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        Preview Image
        {% if article.article_image %}
        <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="resim yok"></a>

        {% endif %}

        <hr>

        <!-- Post Content -->
        <p class="lead">{{article.content|safe|truncatewords:50}}</p>
        <a style='float: right;' href="{% url 'article:detail' article.id %}">devamını oku...</a>
             <hr>

        </div>
     </div>
     {% endfor %}

     {% else %}
     <div class="alert alert-danger">Aranan makale bulunamadı...</div>
    {% endif %}
    </div>
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p> Hoşgeldiniz sayın, <small>{{request.user.username}}</small></p>
<hr>
<a class ='btn btn-success' href='/articles/addarticle'>Makale Ekle</a>
<hr>
{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
  {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href='/articles/article/{{article.id}}'>{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href='/articles/update/{{article.id}}' class ='btn btn-warning'>Güncelle</a></td>
      <td><a href='/articles/delete/{{article.id}}' class ='btn btn-danger'>Sil</a></td>
    </tr>
  {% endfor %}

  </tbody>
</table>
{% else %}
<div class ="alert alert-danger">
Henüz bir makaleniz bulunmuyor...
</div>
{% endif %}

{% endblock %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>

        <!-- Author -->
        <p class="lead">

          <a>Yazar: {{article.author.username}}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        Preview Image
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="resim yok">

        {% endif %}

        <hr>

        <!-- Post Content -->
        <p class="lead">{{article.content|safe}}</p>

        <hr>
        {% if comments %}
        {% for comment in comments %}
        <div class="media mb-4">
          
          <div class="media-body">
            <h6 class="mt-0">{{comment.comment_author}}</h6>
             {{comment.comment_content}}
          </div>
        </div>
        {% endfor %}
        
        {% else %}
        <div>Henüz yorum yok</div>
        {% endif %}
        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Yorum bırakın:</h5>
          <div class="card-body">
            <form method= "post" action="{% url 'article:comment' article.id %}"> {% csrf_token %}
              <div class="form-group">

                 <input  name="comment_author" type="text" class="form-control" placeholder="Adınız" aria-label="Adınız" aria-describedby="basic-addon1">

                <textarea name="comment_content" class="form-control" rows="3" placeholder="Yorumunuzu yazınız..."></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Ekle</button>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">DJANGO BLOG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'about' %}">Hakkımızda</a>
        </li>
         <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'article:articles' %}">Makaleler</a>
        </li>
        </ul>
          <ul class="navbar-nav ml-auto mb-2 mb-md-0">
          <li class="nav-item active">
          <a class="nav-link" aria-current="page" Style="color:#FFFF00;">{{request.user.username}}</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'article:dashboard' %}">Menü</a>
          </li>
          <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'user:logout' %}">Siktir Git</a>
          </li>
          {% else %}
          <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'user:login' %}">Giriş</a>
          </li>
          <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'user:register' %}">Kaydolun</a>
          </li>
          {% endif %}
        </ul>
    </div>
  </div>
</nav>

templates/includes/posttemplate.html
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>

templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class="jumbotron text-center">
  <h1 class="display-4">Merhaba, Bilader!</h1>
  <p class="lead">Burada Django ile bir blog çalışması yapmaktayız</p>
  <hr class="my-4">
</div>


{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Ybblog</title>
</head>
<body>  
        {% include "includes/navbar.html" %}

        

        <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">
                
            {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
            {% block body %}
            
            {% endblock body %}

        </div>
    

      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
         <script>
                        CKEDITOR.replace( 'content',{allowedContent : true} );
                </script>

    </body>
</html>

templates/login.html
{% extends "layout.html" %}


{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method = "post"> 
         {% csrf_token %}
         {{form|crispy}}
         <br>
        <button type="submit" class ="btn btn-warning">Giriş</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/logout.html
{% extends "layout.html" %}

{% block body %}
<h3>Çıkış</h3>
<hr>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method = "post"> 
         {% csrf_token %}
         {{form|crispy}}
         <br>
        <button type="submit" class ="btn btn-warning">Giriş</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="form-group">
    <div class="form-group">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data"> 
         {% csrf_token %}
         {{form|crispy}}
         <br>
        <button type="submit" class ="btn btn-warning">Güncelle</button>
        </form>
    </div>
</div>
{% endblock body %}